<?php

/**
 * Implements hook_field_info_alter().
 *
 */
function required_by_role_field_info_alter(&$info) {
  foreach ($info as $field_type => $field_type_info) {
    $info[$field_type]['instance_settings'] += array(
      'required_by_role' => array(),
    );
  }
}

/**
 * Implements hook_field_widget_form_alter.
 *
 */
function required_by_role_field_widget_form_alter(&$element, &$form_state, $context) {

  if(!$context['instance']['required']) {

    global $user;

    $settings = $context['instance']['settings'];
    $required_by_role = $settings['required_by_role'] ? $settings['required_by_role'] : array();

    $match = array_intersect(array_keys($user->roles) , $required_by_role);

    $element['value']['#required'] = $element['#required'] = !empty($match);

  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 */
function required_by_role_form_field_ui_field_edit_form_alter(&$form, $form_state) {
  $field_name = $form['#field']['field_name'];
  $field = field_info_field($field_name);
  $required_by_role = $form['#instance']['settings']['required_by_role'];
  $label = t('Required per role');
  $title = t('Mandatory per role');
  $description = t('Select one of these options if you want different behavior between roles, elsewhere choose use REQUIRED option.');

  $options = user_roles();
  unset($options[DRUPAL_AUTHENTICATED_RID]);

  $module_path = drupal_get_path('module', 'required_by_role');

  /**
   * Js add, needed because STATES API behaves unproperly in this context hidding required option.
   */

  $attached =array(
    'js' => array(
      $module_path . '/required_by_role.js'
    ),
  );

  $form['instance']['settings']['required_by_role'] = array(
    '#prefix' => '<label>' . $label . '</label>',
    '#type' => 'checkboxes',
    '#options' => $options,
    '#default_value' => $required_by_role,
    '#weight' => $form['instance']['required']['#weight'] + 1,
    '#disabled' => $form['instance']['required']['#default_value'],
    '#attached' => $attached,
    '#description' => $description,
  );

  /**
   * Default value needs allways to be NOT required
   */
  $form['instance']['default_value_widget'][$field_name][LANGUAGE_NONE][0]['#required'] = FALSE;

}
